sudo: true
env:
  - NEO4J_VERSION="3.1.1"
language: java
before_install:
  - wget dist.neo4j.org/neo4j-community-${NEO4J_VERSION}-unix.tar.gz
  - tar -xzf neo4j-community-${NEO4J_VERSION}-unix.tar.gz
  - neo4j-community-${NEO4J_VERSION}/bin/neo4j start &
  - ./wait-for-neo4j.bash
before_script:
  - curl -v -u neo4j:neo4j -X POST localhost:7474/user/neo4j/password -H "Content-type:application/json" -d "{\"password\":\"secret\"}"
jdk:
- openjdk11
script:
- test/run.sh
notifications:
  slack:
    secure: bO6+GEsERXf/EAeI72YAsSmIlx3YR221arLe3qf6gaHEvrCg7JxGUidj2pvEDrNTelO41oX7FSExgJDQud75cOGUt5gxKV71tDUfKeYsBkfBJZVO3tLE5U7YO+xjOw2Rm4alHKYf0YIH67mbVA3/5Ayki78+sxRtsdSN+rC5f9A=
